package com.example.superheroes.villain.model;

import lombok.*;
import org.hibernate.Hibernate;
import org.springframework.data.redis.core.RedisHash;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.util.Objects;
import java.util.UUID;

//@RedisHash("villain")
@Getter
@Setter
@ToString
// @Data, same us above
@Entity
@Table
@AllArgsConstructor
@NoArgsConstructor
public class Villain {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "UUID")
    @Column(nullable = false, updatable = false)
    private UUID id;

    @NotNull(message = "First Name is required")
    private String firstName;

    private String lastName;
    private String house;
    private String knownAs;

    /* auto generated by Intellij*/
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || Hibernate.getClass(this) != Hibernate.getClass(o)) return false;
        Villain villain = (Villain) o;
        return id != null && Objects.equals(id, villain.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
