###
GET http://localhost:8080/api/v1/anti-heroes
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzODcwMTQwOCwiZXhwIjoxNjM4NzM3NDA4fQ.0fIGYdOm7aMABORWlCm5N7wCjzc6MJ_6oZvDib4pKgA

###
DELETE http://localhost:8080/api/v1/anti-heroes/6457a746-8067-422b-bba7-c6ddb675706e
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzODcwMTQwOCwiZXhwIjoxNjM4NzM3NDA4fQ.0fIGYdOm7aMABORWlCm5N7wCjzc6MJ_6oZvDib4pKgA

###
POST http://localhost:8080/api/v1/anti-heroes
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzODcwMTQwOCwiZXhwIjoxNjM4NzM3NDA4fQ.0fIGYdOm7aMABORWlCm5N7wCjzc6MJ_6oZvDib4pKgA

{
  "firstName": "John",
  "lastName": "Doe",
  "knownAs": "JD",
  "house": "Florida"
}

###
PUT http://localhost:8080/api/v1/anti-heroes/c4888505-cf86-4298-977f-fcf9fae1ec36
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huZG9lQGdtYWlsLmNvbSIsImlhdCI6MTYzODcwMTQwOCwiZXhwIjoxNjM4NzM3NDA4fQ.0fIGYdOm7aMABORWlCm5N7wCjzc6MJ_6oZvDib4pKgA

{
  "id": "c4888505-cf86-4298-977f-fcf9fae1ec36",
  "firstName": "John - Updated",
  "lastName": "Doe - Updated",
  "knownAs": "JD - Updated",
  "house": "Florida - Updated"
}

